[ClassVersion("1.0.0.0"), FriendlyName("bManagedCredential")] 
class Codeblack_bManagedCredential : OMI_BaseResource
{
    [Key, Description("The name of the target")] string TargetName;
    [Write, ValueMap{"Present", "Absent"}, Values{"Present", "Absent"}] string Ensure;
    [Write, EmbeddedInstance("MSFT_Credential"),Description("The credential to be used to access the target")] string Credential;
    [Write, ValueMap{"DomainPassword", "DomainCertificate", "DomainVisiblePassword", "GenericCertificate", "DomainExtended", "Maximum", "MaximumEx"}, Values{"DomainPassword", "DomainCertificate", "DomainVisiblePassword", "GenericCertificate", "DomainExtended", "Maximum", "MaximumEx"}] string CredentialType;
    [Write] boolean Persist;
    [Write, ValueMap{"LocalMachine", "Enterprise"}, Values{"LocalMachine", "Enterprise"}] string PersistanceScope;
};
